services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    network_mode: host

  redis:
    image: redis:latest
    container_name: auth-db
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - "6379:6379"
    volumes:
      - auth-volume:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf && 
        cat /usr/local/etc/redis/redis.conf
      '
    network_mode: host
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "3005:3005"
    depends_on:
      - auth
      - profile
      - friends
      - points
    network_mode: host

  auth:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "3004:3004"
    network_mode: host
  
  profile:
    container_name: profile-service
    build: ./profile-service
    ports:
      - "3001:3001"
    network_mode: host

  friends:
    container_name: friends-service
    build: ./friends_service
    ports:
      - "3002:3002"
    network_mode: host

  points:
    container_name: points-service
    build: ./points_service
    ports:
      - "3003:3003"
    network_mode: host

volumes:
  auth-volume:

networks:
  backend:
    driver: bridge